Training
Epoch 1/1 [Train]:   0%|â–Ž                                                                            | 4/1060 [00:01<08:36,  2.04it/s, Loss=0.0322]
Traceback (most recent call last):
  File "/home/vatsal/NWM/fno_sevir/fno_sevir.py", line 73, in <module>
    avg_train_loss.append(loss.item())
                          ~~~~~~~~~^^
KeyboardInterrupt
Exception ignored in atexit callback <function _start_and_connect_service.<locals>.teardown_atexit at 0x727077b3cea0>:
Traceback (most recent call last):
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/vatsal/miniconda3/lib/python3.13/threading.py", line 1092, in join
    self._handle.join(timeout)
KeyboardInterrupt:
Exception ignored in atexit callback <function shutdown_compile_workers at 0x726ff919bc40>:
Traceback (most recent call last):
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/torch/_inductor/async_compile.py", line 113, in shutdown_compile_workers
    pool.shutdown()
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/torch/_inductor/compile_worker/subproc_pool.py", line 239, in shutdown
    self.process.wait(300)
  File "/home/vatsal/miniconda3/lib/python3.13/subprocess.py", line 1289, in wait
    self._wait(timeout=sigint_timeout)
  File "/home/vatsal/miniconda3/lib/python3.13/subprocess.py", line 2062, in _wait
    time.sleep(delay)
KeyboardInterrupt:
