Training
Epoch 1/1 [Train]: 394it [02:17,  2.87it/s, Loss=0.0067]                                                                                           
Epoch 1/1 [Validation]:   0%|                                                                                              | 0/393 [00:00<?, ?it/s]
/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/vatsal/NWM/fno_sevir/fno_sevir.py", line 128, in <module>
    if val_losses < best_val_loss:
                    ^^^^^^^^^^^^^
NameError: name 'best_val_loss' is not defined. Did you mean: 'avg_val_loss'?
