2025-05-29 12:50:50,225 INFO    MainThread:66092 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-05-29 12:50:50,226 INFO    MainThread:66092 [wandb_setup.py:_flush():70] Configure stats pid to 66092
2025-05-29 12:50:50,226 INFO    MainThread:66092 [wandb_setup.py:_flush():70] Loading settings from /home/vatsal/.config/wandb/settings
2025-05-29 12:50:50,226 INFO    MainThread:66092 [wandb_setup.py:_flush():70] Loading settings from /home/vatsal/NWM/DiffCast/wandb/settings
2025-05-29 12:50:50,226 INFO    MainThread:66092 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-05-29 12:50:50,226 INFO    MainThread:66092 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/vatsal/NWM/DiffCast/wandb/run-20250529_125050-96zl6f2n/logs/debug.log
2025-05-29 12:50:50,226 INFO    MainThread:66092 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/vatsal/NWM/DiffCast/wandb/run-20250529_125050-96zl6f2n/logs/debug-internal.log
2025-05-29 12:50:50,226 INFO    MainThread:66092 [wandb_init.py:init():852] calling init triggers
2025-05-29 12:50:50,226 INFO    MainThread:66092 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-29 12:50:50,226 INFO    MainThread:66092 [wandb_init.py:init():893] starting backend
2025-05-29 12:50:50,226 INFO    MainThread:66092 [wandb_init.py:init():897] sending inform_init request
2025-05-29 12:50:50,265 INFO    MainThread:66092 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-29 12:50:50,265 INFO    MainThread:66092 [wandb_init.py:init():907] backend started and connected
2025-05-29 12:50:50,272 INFO    MainThread:66092 [wandb_init.py:init():1005] updated telemetry
2025-05-29 12:50:50,309 INFO    MainThread:66092 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-29 12:50:51,091 INFO    MainThread:66092 [wandb_init.py:init():1104] starting run threads in backend
2025-05-29 12:50:51,228 INFO    MainThread:66092 [wandb_run.py:_console_start():2573] atexit reg
2025-05-29 12:50:51,229 INFO    MainThread:66092 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-29 12:50:51,229 INFO    MainThread:66092 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-29 12:50:51,229 INFO    MainThread:66092 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-29 12:50:51,231 INFO    MainThread:66092 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-29 12:50:51,231 INFO    MainThread:66092 [wandb_run.py:_config_callback():1436] config_cb None None {'backbone': 'earthformer', 'use_diff': True, 'seed': 0, 'exp_dir': 'basic_exps', 'exp_note': None, 'dataset': 'sevir', 'img_size': 384, 'img_channel': 1, 'seq_len': 20, 'frames_in': 10, 'frames_out': 10, 'num_workers': 2, 'lr': 0.0001, 'lr_beta1': 0.9, 'lr_beta2': 0.95, 'l2_norm': 0.0, 'ema_rate': 0.95, 'scheduler': 'cosine', 'warmup_steps': 1000, 'mixed_precision': 'bf16', 'grad_acc_step': 1, 'batch_size': 1, 'epochs': 1, 'training_steps': 20, 'early_stop': 10, 'ckpt_milestone': '/home/vatsal/NWM/DiffCast/Exps/basic_exps/Diffearthformer_sevir_None/checkpoints/ckpt-10000.pt', 'eval': False, 'wandb_state': 'online'}
2025-05-29 12:52:08,572 INFO    MsgRouterThr:66092 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-29 12:52:09,193 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,196 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,197 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,197 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,197 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,198 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,199 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,200 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,200 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,201 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,202 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,202 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,203 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,203 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,204 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-29 12:52:09,204 ERROR   MainThread:66092 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
