2025-06-10 16:22:03,510 INFO    MainThread:112883 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-06-10 16:22:03,510 INFO    MainThread:112883 [wandb_setup.py:_flush():70] Configure stats pid to 112883
2025-06-10 16:22:03,510 INFO    MainThread:112883 [wandb_setup.py:_flush():70] Loading settings from /home/vatsal/.config/wandb/settings
2025-06-10 16:22:03,510 INFO    MainThread:112883 [wandb_setup.py:_flush():70] Loading settings from /home/vatsal/NWM/weather/pipeline/wandb/settings
2025-06-10 16:22:03,510 INFO    MainThread:112883 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-06-10 16:22:03,510 INFO    MainThread:112883 [wandb_init.py:setup_run_log_directory():724] Logging user logs to logs/wandb/run-20250610_162203-j7egtk40/logs/debug.log
2025-06-10 16:22:03,510 INFO    MainThread:112883 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to logs/wandb/run-20250610_162203-j7egtk40/logs/debug-internal.log
2025-06-10 16:22:03,510 INFO    MainThread:112883 [wandb_init.py:init():852] calling init triggers
2025-06-10 16:22:03,511 INFO    MainThread:112883 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-06-10 16:22:03,511 INFO    MainThread:112883 [wandb_init.py:init():893] starting backend
2025-06-10 16:22:03,511 INFO    MainThread:112883 [wandb_init.py:init():897] sending inform_init request
2025-06-10 16:22:03,557 INFO    MainThread:112883 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-06-10 16:22:03,557 INFO    MainThread:112883 [wandb_init.py:init():907] backend started and connected
2025-06-10 16:22:03,564 INFO    MainThread:112883 [wandb_init.py:init():1005] updated telemetry
2025-06-10 16:22:03,603 INFO    MainThread:112883 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-06-10 16:22:04,764 INFO    MainThread:112883 [wandb_init.py:init():1104] starting run threads in backend
2025-06-10 16:22:04,966 INFO    MainThread:112883 [wandb_run.py:_console_start():2573] atexit reg
2025-06-10 16:22:04,967 INFO    MainThread:112883 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-06-10 16:22:04,967 INFO    MainThread:112883 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-06-10 16:22:04,967 INFO    MainThread:112883 [wandb_run.py:_redirect():2513] Redirects installed.
2025-06-10 16:22:04,972 INFO    MainThread:112883 [wandb_init.py:init():1150] run started, returning control to user process
2025-06-10 16:22:36,810 INFO    MainThread:112883 [wandb_run.py:_config_callback():1436] config_cb None None {'model_name': 'DiT'}
2025-06-10 16:23:49,266 INFO    MsgRouterThr:112883 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-06-10 16:23:50,501 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,504 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,505 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,506 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,507 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,507 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,508 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,509 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,510 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,510 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,511 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,512 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,512 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,513 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,513 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-10 16:23:50,513 ERROR   MainThread:112883 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/vatsal/miniconda3/envs/earthformer/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
