Epoch 1/10: 100%|██████████████████████████████████████████| 8929/8929 [26:57<00:00,  5.52it/s, Loss=0.0005, Recon=0.0003, KL=204.7467]
Epoch 1: Loss=0.0029, Recon=0.0020, KL=919.7040
Model saved: /home/vatsal/NWM/fno_sevir/vae_weights/vae_epoch_1.pth
Traceback (most recent call last):
  File "/home/vatsal/NWM/fno_sevir/vae.py", line 256, in <module>
    main()
    ~~~~^^
  File "/home/vatsal/NWM/fno_sevir/vae.py", line 244, in main
    train_vae(vae_model, train_loader, val_loader, optimizer, NUM_EPOCHS)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/fno_sevir/vae.py", line 142, in train_vae
    validate_vae(model, val_loader, epoch)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/fno_sevir/vae.py", line 169, in validate_vae
    plot_reconstruction_comparison(images, reconstructed, epoch, batch_idx, save_wandb=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/fno_sevir/vae.py", line 65, in plot_reconstruction_comparison
    plt.savefig(os.path.join("vaeplots", f"reconstruction_epoch_{epoch+1}_batch_{batch_idx}.png"), dpi=300)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/matplotlib/pyplot.py", line 1251, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/matplotlib/figure.py", line 3490, in savefig
    self.canvas.print_figure(fname, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/matplotlib/backend_bases.py", line 2184, in print_figure
    result = print_method(
        filename,
    ...<3 lines>...
        bbox_inches_restore=_bbox_inches_restore,
        **kwargs)
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/matplotlib/backend_bases.py", line 2040, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ~~~~^
        *args, **{k: v for k, v in kwargs.items() if k not in skip}))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/matplotlib/backends/backend_agg.py", line 481, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/matplotlib/backends/backend_agg.py", line 430, in _print_pil
    mpl.image.imsave(
    ~~~~~~~~~~~~~~~~^
        filename_or_obj, self.buffer_rgba(), format=fmt, origin="upper",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/matplotlib/image.py", line 1657, in imsave
    image.save(fname, **pil_kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/PIL/Image.py", line 2576, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'vaeplots/reconstruction_epoch_1_batch_0.png'
